import type { Metadata } from "next";
import { Geist, Geist_Mono, Lora, Playfair_Display, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const lora = Lora({ subsets: ['latin'], variable: '--font-serif' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playFair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const IBMPlex = IBM_Plex_Mono({
  variable: "--font-ibm-plex",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", playFair.variable, geistSans.variable, IBMPlex.variable, "font-serif", lora.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
